application: alwaysrdg
version: b1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static #min
- url: /
  static_files: static/index.html #min/index.html
  upload: min/index.html
- url: /.*
  script: ar2.py
